name: omega-linux # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.48.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Multiplayer Battletech combat simulator
description: |
  The MegaMek suite of programs allow you to play out tactical turn-based battles and military campaigns in the BattleTech Universe, with tanks, infantry, battle armor, aerospace fighters, WarShips, and most importantly, the mighty BattleMech™ -- king of the battlefield. The programs provide a modern, computerized version of the BattleTech tabletop game, as well as a variety of features for running campaigns and customizing units. 

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  omega_icon.png
title: MegaMek

apps:
  omega:
    command: omega
parts:
  omega:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      omega: build/
      omega.1: man/man1/

architectures:
  - build-on: amd64

