name: omega-linux # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.90.pa8' # just for humans, typically '1.2+git' or '1.3.2'
summary:  The classic Roguelike game.
description: |
   The classic Roguelike game. You start out in the city of Rampart as a new player and must choose which guilds you want to be a member of. The oracle may provide guidance, but the game itself is pretty much free play. You get your name in the high scores by becoming the leader of your guild or other group or by getting a high enough score.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  omega_icon.png
title: Omega

apps:
  omega:
    command: omega
parts:
  omega:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      omega: build/
      omega.1: man/man1/

architectures:
  - build-on: amd64

